version: '3.8'

services:
  marchat:
    image: codecodesxyz/marchat:v0.2.0-beta.4
    container_name: marchat-server
    restart: unless-stopped
    
    # Port mapping
    ports:
      - "8080:8080"
    
    # Environment variables for configuration
    environment:
      # Required: Admin authentication
      - MARCHAT_ADMIN_KEY=${MARCHAT_ADMIN_KEY:-changeme}
      - MARCHAT_USERS=${MARCHAT_USERS:-admin}
      
      # Optional: Server configuration
      - MARCHAT_PORT=8080
      - MARCHAT_LOG_LEVEL=info
      
      # Database and config paths (relative to mounted volume)
      - MARCHAT_CONFIG_DIR=/marchat/config
      - MARCHAT_DB_PATH=/marchat/config/marchat.db
      
      # TLS configuration (if using TLS)
      - MARCHAT_TLS_CERT_FILE=/marchat/config/cert.pem
      - MARCHAT_TLS_KEY_FILE=/marchat/config/key.pem
    
    # Volume mounting for persistent data
    volumes:
      # Mount local directory to container config path
      # This allows persistent storage of database, config files, and TLS certificates
      - ./appdata/marchat:/marchat/config:rw
      
      # Optional: Mount plugin directory for custom plugins
      - ./appdata/marchat/plugins:/marchat/config/plugins:rw
    
    # Security: Run as non-root user (if supported by image)
    # user: "1000:1000"  # Uncomment if your image supports non-root user
    
    # Health check
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Instructions for setup:
#
# 1. Create the local directory structure:
#    mkdir -p ./appdata/marchat/plugins
#
# 2. Set proper permissions (Linux/Unraid):
#    # For Linux systems, ensure the directory is writable by the container user
#    chown -R 1000:1000 ./appdata/marchat
#    chmod -R 755 ./appdata/marchat
#    
#    # For Unraid systems, you may need to adjust permissions:
#    chmod -R 777 ./appdata/marchat  # Less secure but often needed for Unraid
#
# 3. Generate secure admin key:
#    openssl rand -hex 32
#
# 4. Create .env file with your configuration:
#    MARCHAT_ADMIN_KEY=your-generated-key-here
#    MARCHAT_USERS=admin1,admin2
#
# 5. For TLS support, place your certificate files in ./appdata/marchat/:
#    - cert.pem (TLS certificate)
#    - key.pem (TLS private key)
#
# 6. Start the service:
#    docker-compose -f docker-compose.example.yml up -d
#
# 7. Verify the service is running:
#    docker-compose -f docker-compose.example.yml logs -f 