services:
  marchat:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./config:/marchat/config
      - marchat_data:/marchat/config
    environment:
      - MARCHAT_PORT=8080
      - MARCHAT_ADMIN_KEY=changeme
      - MARCHAT_USERS=Cody,Crystal
      - MARCHAT_DB_PATH=/marchat/config/marchat.db
      - MARCHAT_LOG_LEVEL=info
      - MARCHAT_JWT_SECRET=your-jwt-secret-change-in-production
    restart: unless-stopped
    # Alternative: mount a .env file instead of using environment block
    # env_file:
    #   - .env

volumes:
  marchat_data:
