name: Go CI & Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'   # trigger release on semantic version tags
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'

      - name: Tidy modules
        run: go mod tidy

      - name: Build
        run: go build ./...

      - name: Test
        run: go test ./...

      - name: Lint (golangci-lint if available, else go vet)
        run: |
          if go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest 2>/dev/null; then
            $(go env GOPATH)/bin/golangci-lint run ./...
          else
            go vet ./...
          fi

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install goreleaser
        run: |
          curl -sSfL https://goreleaser.com/install.sh | sh

      - name: Run goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goreleaser release --rm-dist
